blueprint:
  name: Philips Hue Dimmer Switch
  description: |
    Use the Philips Hue Dimmer Switch as 3 scene buttons (short press on/up/down),
    brightness control (hold up/down), and an off button (short press off).
  domain: automation
  source_url: https://github.com/Minnozz/home-assistant-config/blob/main/blueprints/hue-dimmer-switch.yaml
  input:
    dimmer_device:
      name: Dimmer Switch Device
      description: "The Hue Dimmer Switch to configure"
      selector:
        device:
          integration: hue
    target_light:
      name: Target Lights
      description: "Target lights used for the off button and brightness control"
      selector:
        target:
          entity:
            - domain: light
    scene_on:
      name: On Button
      description: "Scene to set when pushing the On button"
      selector:
        target:
          entity:
            - domain: scene
    scene_up:
      name: Up Button
      description: "Scene to set when pushing the Brightness Up button"
      selector:
        target:
          entity:
            - domain: scene
    scene_down:
      name: Down Button
      description: "Scene to set when pushing the Brightness Down button"
      selector:
        target:
          entity:
            - domain: scene
    brightness_step_pct:
      name: Brightness step size
      description: "Percentage of brightness to change per tick (~ second)"
      default: 20
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider

mode: parallel

trigger:
  - device_id: !input dimmer_device
    domain: hue
    platform: device
    type: initial_press
    subtype: 1
    id: on_pressed
  - device_id: !input dimmer_device
    domain: hue
    platform: device
    type: short_release
    subtype: 2
    id: up_pressed
  - device_id: !input dimmer_device
    domain: hue
    platform: device
    type: repeat
    subtype: 2
    id: up_tick
  - device_id: !input dimmer_device
    domain: hue
    platform: device
    type: short_release
    subtype: 3
    id: down_pressed
  - device_id: !input dimmer_device
    domain: hue
    platform: device
    type: repeat
    subtype: 3
    id: down_tick
  - device_id: !input dimmer_device
    domain: hue
    platform: device
    type: initial_press
    subtype: 4
    id: off_pressed

condition: []

variables:
  brightness_step_pct: !input brightness_step_pct

action:
  - choose:
      - conditions:
          - condition: trigger
            id: on_pressed
        sequence:
          - service: scene.turn_on
            target: !input scene_on
            data:
              transition: 1
      - conditions:
          - condition: trigger
            id: up_pressed
        sequence:
          - service: scene.turn_on
            target: !input scene_up
            data:
              transition: 1
      - conditions:
          - condition: trigger
            id: down_pressed
        sequence:
          - service: scene.turn_on
            target: !input scene_down
            data:
              transition: 1
      - conditions:
          - condition: trigger
            id: up_tick
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_step_pct: "{{ brightness_step_pct }}"
              transition: 1
      - conditions:
          - condition: trigger
            id: down_tick
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_step_pct: "{{ -1 * brightness_step_pct }}"
              transition: 1
      - conditions:
          - condition: trigger
            id: off_pressed
        sequence:
          - service: light.turn_off
            target: !input target_light
            data:
              transition: 1
    default:
      - service: persistent_notification.create
        data:
          message:
            Hue Dimmer Switch ran default event from "choose" action on button press!
          notification_id: hue_dimmer_switch_blueprint
          title: Uncaught Dimmer Command