blueprint:
  name: Philips Hue Dimmer Switch (zigbee2mqtt integration)
  description: |
    Philips Hue Dimmer Switch:
    - 3 scene buttons (short press on/up/down)
    - brightness control (hold up/down)
    - off button (short press off)
  domain: automation
  source_url: https://github.com/Minnozz/home-assistant-config/blob/main/blueprints/hue-dimmer-switch-zigbee2mqtt.yaml
  input:
    dimmer_action:
      name: Dimmer Switch Action Sensor
      description: "The action indicating the button press on the Hue Dimmer Switch to configure"
      selector:
        entity:
          integration: mqtt
          domain: sensor
          multiple: true
    target_light:
      name: Target Lights
      description: "Target lights used for the off button and brightness control"
      selector:
        target:
          entity:
            - domain: light
    scene_on:
      name: On Button
      description: "Scene to set when pushing the On button"
      selector:
        target:
          entity:
            - domain: scene
    scene_up:
      name: Up Button
      description: "Scene to set when pushing the Brightness Up button"
      selector:
        target:
          entity:
            - domain: scene
    scene_down:
      name: Down Button
      description: "Scene to set when pushing the Brightness Down button"
      selector:
        target:
          entity:
            - domain: scene
    brightness_step_pct:
      name: Brightness step size
      description: "Percentage of brightness to change per tick (~ second)"
      default: 20
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider

mode: parallel

trigger:
  - platform: state
    entity_id: !input dimmer_action
    to: "on_press_release"
    id: on_pressed
  - platform: state
    entity_id: !input dimmer_action
    to: "up_press_release"
    id: up_pressed
  - platform: state
    entity_id: !input dimmer_action
    to: "up_hold"
    id: up_tick
  - platform: state
    entity_id: !input dimmer_action
    to: "down_press_release"
    id: down_pressed
  - platform: state
    entity_id: !input dimmer_action
    to: "down_hold"
    id: down_tick
  - platform: state
    entity_id: !input dimmer_action
    to: "off_press_release"
    id: off_pressed

condition: []

variables:
  brightness_step_pct: !input brightness_step_pct

action:
  - choose:
      - conditions:
          - condition: trigger
            id: on_pressed
        sequence:
          - service: scene.turn_on
            target: !input scene_on
            data:
              transition: 1
      - conditions:
          - condition: trigger
            id: up_pressed
        sequence:
          - service: scene.turn_on
            target: !input scene_up
            data:
              transition: 1
      - conditions:
          - condition: trigger
            id: down_pressed
        sequence:
          - service: scene.turn_on
            target: !input scene_down
            data:
              transition: 1
      - conditions:
          - condition: trigger
            id: up_tick
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_step_pct: "{{ brightness_step_pct }}"
              transition: 1
      - conditions:
          - condition: trigger
            id: down_tick
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_step_pct: "{{ -1 * brightness_step_pct }}"
              transition: 1
      - conditions:
          - condition: trigger
            id: off_pressed
        sequence:
          - service: light.turn_off
            target: !input target_light
            data:
              transition: 1
    default:
      - service: persistent_notification.create
        data:
          message:
            Hue Dimmer Switch ran default event from "choose" action on button press!
          notification_id: hue_dimmer_switch_blueprint
          title: Uncaught Dimmer Command
